'use client';
import {useEffect,useRef,useState} from 'react';
import {ImagePlus,Check,ChevronRight,ArrowLeft,X,LoaderCircle,FolderOpen,CheckCircle2} from 'lucide-react';
import {ancestorsOf} from '../lib/gallery-navigation';
import {missingGalleryFields,publicationStatuses,galleryCoverUrl} from '../lib/gallery-completion';
export type CompletionPhoto={id:string;name:string;urls?:Record<string,string>;alt?:string};
export type CompletionGallery={id:string;name:string;tags:string[];status:string;featuredPhoto?:CompletionPhoto;parentId?:string;subGalleries?:CompletionGallery[];photos?:CompletionPhoto[]};
type Changes={tags?:string[];status?:string;featuredPhotoId?:string};
type Props={galleries:CompletionGallery[];allGalleries:CompletionGallery[];loadGallery:(id:string)=>Promise<CompletionGallery>;onSave:(id:string,changes:Changes,cover?:CompletionPhoto)=>Promise<void>;onOpen:(id:string)=>void};
function CoverPicker({target,allGalleries,loadGallery,onChoose,onClose}:{target:CompletionGallery;allGalleries:CompletionGallery[];loadGallery:Props['loadGallery'];onChoose:(p:CompletionPhoto)=>void;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[current,setCurrent]=useState(target.id),[detail,setDetail]=useState<CompletionGallery|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[limit,setLimit]=useState(60);
 useEffect(()=>{const node=dialog.current;node?.showModal();return()=>node?.close();},[]);
 useEffect(()=>{let active=true;setBusy(true);setError('');setDetail(null);setLimit(60);loadGallery(current).then(g=>{if(active)setDetail(g);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[current,loadGallery]);
 const path=ancestorsOf(current,allGalleries),parent=path.at(-1),meta=allGalleries.find(g=>g.id===current),children=allGalleries.filter(g=>g.parentId===current),photos=detail?.photos||[];
 return <dialog ref={dialog} aria-label="Choisir une vignette" className="cover-picker" onCancel={onClose} onClose={onClose}><div className="modal-head"><div><h2>Choisir une vignette</h2><small>Pour « {target.name} »</small></div><button className="icon-button" aria-label="Fermer le choix de vignette" onClick={onClose}><X size={20}/></button></div><div className="cover-navigation"><button disabled={!parent&&current===target.id} onClick={()=>setCurrent(parent?.id||target.id)} aria-label="Galerie précédente"><ArrowLeft size={17}/></button><strong>{meta?.name||detail?.name||target.name}</strong><select aria-label="Parcourir une autre galerie" value={current} onChange={e=>setCurrent(e.target.value)}>{allGalleries.map(g=><option key={g.id} value={g.id}>{[...ancestorsOf(g.id,allGalleries).map(x=>x.name),g.name].join(' / ')}</option>)}</select></div><div className="cover-picker-body">{children.length>0&&<div className="cover-folders">{children.map(g=><button key={g.id} onClick={()=>setCurrent(g.id)}><FolderOpen size={17}/>{g.name}<ChevronRight size={15}/></button>)}</div>}{busy?<div className="cover-empty"><LoaderCircle className="spin"/> Chargement des photos…</div>:error?<p className="review-error">{error}</p>:photos.length===0?<div className="cover-empty">Aucune photo directe. Ouvrez une sous-galerie ou choisissez une autre galerie.</div>:<div className="cover-options">{photos.slice(0,limit).map(p=>{const src=galleryCoverUrl(p);return <button key={p.id} disabled={!src} onClick={()=>onChoose(p)} title={p.name} aria-label={'Choisir '+p.name}>{src?<img src={src} alt={p.alt||p.name} loading="lazy" decoding="async"/>:<ImagePlus size={25}/>}<span>{p.name}</span></button>;})}</div>}{photos.length>limit&&<button className="button cover-more" onClick={()=>setLimit(x=>x+60)}>Afficher plus de photos ({photos.length-limit})</button>}</div></dialog>;
}
function CompletionRow({gallery,allGalleries,loadGallery,onSave,onOpen}:Props&{gallery:CompletionGallery}){
 const [tags,setTags]=useState((gallery.tags||[]).join(', ')),[status,setStatus]=useState(gallery.status||''),[cover,setCover]=useState<CompletionPhoto|undefined>(gallery.featuredPhoto),[picking,setPicking]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const missing=missingGalleryFields(gallery),tagList=tags.split(',').map(t=>t.trim()).filter(Boolean),tagsChanged=JSON.stringify(tagList)!==JSON.stringify(gallery.tags||[]),coverChanged=cover?.id!==gallery.featuredPhoto?.id,statusChanged=status!==(gallery.status||'');const dirty=tagsChanged||coverChanged||statusChanged;const parentPath=ancestorsOf(gallery.id,allGalleries).map(g=>g.name).join(' / ');const src=galleryCoverUrl(cover);const validStatus=publicationStatuses.includes(status as typeof publicationStatuses[number]);
 async function save(){setSaving(true);setError('');try{const changes:Changes={};if(tagsChanged)changes.tags=tagList;if(statusChanged&&validStatus)changes.status=status;if(coverChanged&&cover)changes.featuredPhotoId=cover.id;await onSave(gallery.id,changes,cover);}catch(e){setError((e as Error).message||'Enregistrement impossible.');}finally{setSaving(false);}}
 return <article className="completion-row"><div className="review-name">{parentPath&&<small title={parentPath}>{parentPath}</small>}<button title="Ouvrir la galerie" onClick={()=>onOpen(gallery.id)}>{gallery.name}<ChevronRight size={16}/></button><div className="missing-chips">{missing.map(label=><span key={label}>{label} à compléter</span>)}</div></div><div className="review-cover"><span className="review-field-label">Vignette</span><button className={!cover?'missing-cover':''} aria-label={'Choisir la vignette de '+gallery.name} disabled={saving} onClick={()=>setPicking(true)}>{src?<img src={src} alt="Vignette de la galerie" loading="lazy"/>:<ImagePlus size={22}/>}<span>{cover?'Changer':'Choisir'}</span></button></div><label className="review-tags">{gallery.parentId?'Tags (facultatifs)':'Tags'}<input aria-label={'Tags de '+gallery.name} disabled={saving} value={tags} onChange={e=>setTags(e.target.value)} placeholder="mariage, portrait…"/><small>Séparés par des virgules</small></label><label className="review-status">Publication<select aria-label={'Statut de '+gallery.name} disabled={saving} value={validStatus?status:''} onChange={e=>setStatus(e.target.value)}><option value="" disabled>Choisir un statut</option><option value="public">Public</option><option value="private">Privé</option><option value="non-reference">Non référencé</option></select></label><button className="button review-save" disabled={!dirty||saving} onClick={save}>{saving?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>}<span>{saving?'Enregistrement…':'Enregistrer'}</span></button>{error&&<p role="alert" className="review-error">{error}</p>}{picking&&<CoverPicker target={gallery} allGalleries={allGalleries} loadGallery={loadGallery} onChoose={p=>{setCover(p);setPicking(false);}} onClose={()=>setPicking(false)}/>}</article>;
}
export default function GalleryCompletion(props:Props){const [limit,setLimit]=useState(40);return <section className="completion-list" aria-label="Galeries à compléter">{props.galleries.length===0?<div className="completion-done"><CheckCircle2 size={34}/><h2>Aucune galerie à compléter dans cette vue</h2><p>Une galerie quitte cette liste dès que ses champs requis sont renseignés. Les tags sont facultatifs pour les sous-galeries.</p></div>:<><p className="review-intro">Complétez les champs manquants, puis enregistrez. Une galerie complète disparaît de cette liste.</p>{props.galleries.slice(0,limit).map(g=><CompletionRow key={g.id} {...props} gallery={g}/>)}{props.galleries.length>limit&&<button className="button cover-more" onClick={()=>setLimit(n=>n+40)}>Afficher les suivantes ({props.galleries.length-limit})</button>}</>}</section>;}
