'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,Share,PlusSquare,X,WifiOff,Check} from 'lucide-react';
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export default function Pwa(){
 const [prompt,setPrompt]=useState<InstallEvent|null>(null),[installed,setInstalled]=useState(false),[help,setHelp]=useState(false),[ios,setIos]=useState(false),[offline,setOffline]=useState(false),[installing,setInstalling]=useState(false);const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const media=matchMedia('(display-mode: standalone)');const check=()=>setInstalled(media.matches||(navigator as Navigator&{standalone?:boolean}).standalone===true);check();setIos(/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1));const before=(e:Event)=>{e.preventDefault();setPrompt(e as InstallEvent);};const done=()=>{setInstalled(true);setPrompt(null);setHelp(false);};const connection=()=>setOffline(!navigator.onLine);connection();window.addEventListener('beforeinstallprompt',before);window.addEventListener('appinstalled',done);window.addEventListener('online',connection);window.addEventListener('offline',connection);media.addEventListener('change',check);
 if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js',{scope:'/',updateViaCache:'none'}).then(reg=>reg.update()).catch(()=>{/* Installation still works where service workers are restricted. */});
 return()=>{window.removeEventListener('beforeinstallprompt',before);window.removeEventListener('appinstalled',done);window.removeEventListener('online',connection);window.removeEventListener('offline',connection);media.removeEventListener('change',check);};},[]);
 useEffect(()=>{if(help){dialog.current?.showModal();}else if(dialog.current?.open)dialog.current.close();},[help]);
 async function install(){if(!prompt){setHelp(true);return;}setInstalling(true);try{await prompt.prompt();const result=await prompt.userChoice;if(result.outcome==='accepted')setInstalled(true);}catch{setHelp(true);}finally{setPrompt(null);setInstalling(false);}}
 return <>{offline&&<div role="status" className="offline-banner"><WifiOff size={16}/> Hors connexion. Reconnectez-vous pour charger ou modifier vos photos.</div>}{!installed&&<button ref={trigger} className="pwa-install" onClick={install} disabled={installing}><Download size={16}/><span>Installer</span></button>}<dialog ref={dialog} className="install-dialog" onCancel={()=>setHelp(false)} onClose={()=>{setHelp(false);trigger.current?.focus();}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)setHelp(false);}}}><div className="modal-head"><h2>Installer Pierre Studio</h2><button className="icon-button" aria-label="Fermer" onClick={()=>setHelp(false)}><X size={21}/></button></div><div className="install-body"><img src="/icons/icon-192.png" width="68" height="68" alt="Pierre Studio"/><p>Retrouvez votre studio directement sur votre écran d’accueil, dans sa propre fenêtre.</p>{ios?<ol><li>Ouvrez ce site dans <strong>Safari</strong>.</li><li>Touchez <strong>Partager</strong> <Share size={16}/> dans le menu du navigateur.</li><li>Choisissez <strong>Sur l’écran d’accueil</strong> <PlusSquare size={16}/>, puis <strong>Ajouter</strong>.</li></ol>:<ol><li>Ouvrez le menu de votre navigateur.</li><li>Choisissez <strong>Installer l’application</strong> ou <strong>Ajouter à l’écran d’accueil</strong>, si cette option est disponible.</li><li>Confirmez l’installation de <strong>Pierre Studio</strong>.</li></ol>}<p className="install-note">L’accès reste privé. Une connexion internet est nécessaire pour consulter et gérer les photos.</p><button className="button primary" onClick={()=>setHelp(false)}><Check size={16}/> Compris</button></div></dialog></>;
}
